### ISSUE TITLE
How the conversion process takes place ?

### ISSUE THREAD

**Issue by sauravtii** [Dengyu-Wu/spkeras#6]
Hi, I have used SpKeras for a couple of applications, but still I am not sure of the conversion process from a CNN to SNN. I did refer [this](https://github.com/Dengyu-Wu/spkeras/blob/master/spkeras/models.py) code, but wasn't able to get any satisfactory insights. So, can anyone help me on this ?

**Comment by Dengyu-Wu** [comment]
Hi sauravtii, 

For the conversion, you can learn the basic ideas from our [paper](https://www.frontiersin.org/articles/10.3389/fnins.2022.759900/full), which explains the importance of the maximum value of activation in each layer and thresholding mechanism.  For the code, it is mainly based on two functions, "convert" for inserting&removing layer and "findlambda" for finding the maximum value for each ReLU layer. You can try to go through the paper and these two functions, and see if they may help.
